# Generated by Django 6.1 on 2026-08-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
    ]
