@baseUrl = http://127.0.0.1:8000

### TASK 04 - Add one product
POST {{baseUrl}}/api/products/
Content-Type: application/json

{
  "name": "Keyboard",
  "price": "79.99"
}

### TASK 04 - Add one product
POST {{baseUrl}}/api/products/
Content-Type: application/json

{
  "name": "Mouse",
  "price": "29.99"
}

### TASK 04 - Add one product
POST {{baseUrl}}/api/products/
Content-Type: application/json

{
  "name": "Processor",
  "price": "149.99"
}

### TASK 04 - List products
GET {{baseUrl}}/api/products/
