### TASK 10 - Get a new JWT token
# @name login

POST http://127.0.0.1:8000/auth/jwt/create/
Content-Type: application/json

{
  "username": "nowy_uzytkownik",
  "password": "bardzoTrudneHaslo123"
}

### TASK 10 - Test the protected endpoint with the original access token
GET http://127.0.0.1:8000/user/
Authorization: Bearer {{login.response.body.access}}

### TASK 10 - Use refresh to get a new access token

# @name refresh
POST http://127.0.0.1:8000/auth/jwt/refresh/
Content-Type: application/json

{
  "refresh": "{{login.response.body.refresh}}"
}

### TASK 10 - Test the protected endpoint with the refreshed access token
GET http://127.0.0.1:8000/user/
Authorization: Bearer {{refresh.response.body.access}}
